# Generated by Django 5.0.1 on 2024-10-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='c01a9d2e-fed1-4fdd-a110-c0c15e9be491', max_length=250),
        ),
    ]
