# Generated by Django 5.0.1 on 2024-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, default='e5e5121c-f9e2-4e9d-ac62-645cd9b43c5c', max_length=250),
        ),
    ]
